name: Run Tests

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    # runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install kani and verify-rust-std
        run: |
          git submodule update --init --recursive verify-rust-std
          ./.github/install-kani.sh

      - name: Install distributed-verification
        run: cargo install --path . --locked

      - name: Verify Rust Std
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./.github/gen_core.json.sh

      - name: View core.json
        working-directory: assets/json
        run: |
          ls -alh core.json
          head -n 100 core.json

      - name: Upload core.json
        uses: actions/upload-artifact@v4
        with:
          name: artifact-libcore
          path: |
            assets/json
            assets/core.sqlite3
          compression-level: 9
          if-no-files-found: error

      - name: Run tests
        run: cargo test -- --nocapture

  kani-list:
    name: kani-list${{ matrix.autoharness }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        autoharness: ["", "-autoharness"]
    if: true
    env:
      UNSTABLE_ARGS: -Z function-contracts -Z mem-predicates -Z float-lib -Z c-ffi -Z loop-contracts -Z quantifiers -Z stubbing
      AUTO: ${{ matrix.autoharness }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install kani
        run: bash ./.github/install-kani.sh

      - name: Kani list
        working-directory: verify-rust-std
        if: env.AUTO == ''
        run:  kani list ${{ env.UNSTABLE_ARGS }} --std ./library --format=json

      - name: Kani list with Autoharness
        working-directory: verify-rust-std
        if: env.AUTO == '-autoharness'
        run: |
          kani autoharness -Z autoharness --list ${{ env.UNSTABLE_ARGS }} --std ./library --format=json \
            --include-pattern "<(.+)[[:space:]]as[[:space:]](.+)>::disjoint_bitor" \
            --include-pattern "<(.+)[[:space:]]as[[:space:]](.+)>::unchecked_disjoint_bitor" \
            --include-pattern "<(.+)[[:space:]]as[[:space:]]iter::range::Step>::backward_unchecked" \
            --include-pattern "<(.+)[[:space:]]as[[:space:]]iter::range::Step>::forward_unchecked" \
            --include-pattern alloc::__default_lib_allocator:: \
            --include-pattern alloc::layout::Layout::from_size_align \
            --include-pattern ascii::ascii_char::AsciiChar::from_u8 \
            --include-pattern char::convert::from_u32_unchecked \
            --include-pattern core_arch::x86::__m128d::as_f64x2 \
            --include-pattern "convert::num::<impl.convert::From<num::nonzero::NonZero<" \
            --include-pattern "num::<impl.i8>::unchecked_add" \
            --include-pattern "num::<impl.i16>::unchecked_add" \
            --include-pattern "num::<impl.i32>::unchecked_add" \
            --include-pattern "num::<impl.i64>::unchecked_add" \
            --include-pattern "num::<impl.i128>::unchecked_add" \
            --include-pattern "num::<impl.isize>::unchecked_add" \
            --include-pattern "num::<impl.u8>::unchecked_add" \
            --include-pattern "num::<impl.u16>::unchecked_add" \
            --include-pattern "num::<impl.u32>::unchecked_add" \
            --include-pattern "num::<impl.u64>::unchecked_add" \
            --include-pattern "num::<impl.u128>::unchecked_add" \
            --include-pattern "num::<impl.usize>::unchecked_add" \
            --include-pattern "num::<impl.i8>::unchecked_neg" \
            --include-pattern "num::<impl.i16>::unchecked_neg" \
            --include-pattern "num::<impl.i32>::unchecked_neg" \
            --include-pattern "num::<impl.i64>::unchecked_neg" \
            --include-pattern "num::<impl.i128>::unchecked_neg" \
            --include-pattern "num::<impl.isize>::unchecked_neg" \
            --include-pattern "num::<impl.i8>::unchecked_sh" \
            --include-pattern "num::<impl.i16>::unchecked_sh" \
            --include-pattern "num::<impl.i32>::unchecked_sh" \
            --include-pattern "num::<impl.i64>::unchecked_sh" \
            --include-pattern "num::<impl.i128>::unchecked_sh" \
            --include-pattern "num::<impl.isize>::unchecked_sh" \
            --include-pattern "num::<impl.u8>::unchecked_sh" \
            --include-pattern "num::<impl.u16>::unchecked_sh" \
            --include-pattern "num::<impl.u32>::unchecked_sh" \
            --include-pattern "num::<impl.u64>::unchecked_sh" \
            --include-pattern "num::<impl.u128>::unchecked_sh" \
            --include-pattern "num::<impl.usize>::unchecked_sh" \
            --include-pattern "num::<impl.i8>::unchecked_sub" \
            --include-pattern "num::<impl.i16>::unchecked_sub" \
            --include-pattern "num::<impl.i32>::unchecked_sub" \
            --include-pattern "num::<impl.i64>::unchecked_sub" \
            --include-pattern "num::<impl.i128>::unchecked_sub" \
            --include-pattern "num::<impl.isize>::unchecked_sub" \
            --include-pattern "num::<impl.u8>::unchecked_sub" \
            --include-pattern "num::<impl.u16>::unchecked_sub" \
            --include-pattern "num::<impl.u32>::unchecked_sub" \
            --include-pattern "num::<impl.u64>::unchecked_sub" \
            --include-pattern "num::<impl.u128>::unchecked_sub" \
            --include-pattern "num::<impl.usize>::unchecked_sub" \
            --include-pattern "num::<impl.i8>::wrapping_sh" \
            --include-pattern "num::<impl.i16>::wrapping_sh" \
            --include-pattern "num::<impl.i32>::wrapping_sh" \
            --include-pattern "num::<impl.i64>::wrapping_sh" \
            --include-pattern "num::<impl.i128>::wrapping_sh" \
            --include-pattern "num::<impl.isize>::wrapping_sh" \
            --include-pattern "num::<impl.u8>::wrapping_sh" \
            --include-pattern "num::<impl.u16>::wrapping_sh" \
            --include-pattern "num::<impl.u32>::wrapping_sh" \
            --include-pattern "num::<impl.u64>::wrapping_sh" \
            --include-pattern "num::<impl.u128>::wrapping_sh" \
            --include-pattern "num::<impl.usize>::wrapping_sh" \
            --include-pattern "num::nonzero::NonZero::<i8>::count_ones" \
            --include-pattern "num::nonzero::NonZero::<i16>::count_ones" \
            --include-pattern "num::nonzero::NonZero::<i32>::count_ones" \
            --include-pattern "num::nonzero::NonZero::<i64>::count_ones" \
            --include-pattern "num::nonzero::NonZero::<i128>::count_ones" \
            --include-pattern "num::nonzero::NonZero::<isize>::count_ones" \
            --include-pattern "num::nonzero::NonZero::<u8>::count_ones" \
            --include-pattern "num::nonzero::NonZero::<u16>::count_ones" \
            --include-pattern "num::nonzero::NonZero::<u32>::count_ones" \
            --include-pattern "num::nonzero::NonZero::<u64>::count_ones" \
            --include-pattern "num::nonzero::NonZero::<u128>::count_ones" \
            --include-pattern "num::nonzero::NonZero::<usize>::count_ones" \
            --include-pattern "num::nonzero::NonZero::<i8>::rotate_" \
            --include-pattern "num::nonzero::NonZero::<i16>::rotate_" \
            --include-pattern "num::nonzero::NonZero::<i32>::rotate_" \
            --include-pattern "num::nonzero::NonZero::<i64>::rotate_" \
            --include-pattern "num::nonzero::NonZero::<i128>::rotate_" \
            --include-pattern "num::nonzero::NonZero::<isize>::rotate_" \
            --include-pattern "num::nonzero::NonZero::<u8>::rotate_" \
            --include-pattern "num::nonzero::NonZero::<u16>::rotate_" \
            --include-pattern "num::nonzero::NonZero::<u32>::rotate_" \
            --include-pattern "num::nonzero::NonZero::<u64>::rotate_" \
            --include-pattern "num::nonzero::NonZero::<u128>::rotate_" \
            --include-pattern "num::nonzero::NonZero::<usize>::rotate_" \
            --include-pattern ptr::align_offset::mod_inv \
            --include-pattern ptr::alignment::Alignment::as_nonzero \
            --include-pattern ptr::alignment::Alignment::as_usize \
            --include-pattern ptr::alignment::Alignment::log2 \
            --include-pattern ptr::alignment::Alignment::mask \
            --include-pattern ptr::alignment::Alignment::new \
            --include-pattern ptr::alignment::Alignment::new_unchecked \
            --include-pattern time::Duration::from_micros \
            --include-pattern time::Duration::from_millis \
            --include-pattern time::Duration::from_nanos \
            --exclude-pattern time::Duration::from_nanos_u128 \
            --include-pattern time::Duration::from_secs \
            --exclude-pattern time::Duration::from_secs_f \
            --include-pattern unicode::unicode_data::conversions::to_ \
            --exclude-pattern ::precondition_check \
            -Z unstable-options --harness-timeout 10m \
            --default-unwind 1000 \

      - name: View list
        working-directory: verify-rust-std
        run: ls -alh kani-list.json && head -n 100 kani-list.json

      - name: Upload kani-list.json
        uses: actions/upload-artifact@v4
        with:
          name: artifact-kani-list${{ env.AUTO }}
          path: verify-rust-std/kani-list.json
          compression-level: 9
          if-no-files-found: error
